"""
Refined Example 4: Legendary Fantasy Broadsword (20x20)
Focus: 100% perfectly straight vertical blade, razor bevel, golden crossguard,
wrapped leather grip, and jeweled pommel.
"""

from pixelcraft import Canvas, Palette, print_ansi, save_png, lint_sprite

palette = Palette({
    ".": None,
    "#": "#140c1c",
    "W": "#ffffff",
    "s": "#deeed6",
    "S": "#8595a1",
    "D": "#4e4a4e",
    "G": "#edad54",
    "g": "#d27d2c",
    "R": "#d04648",
    "L": "#854c30",
    "l": "#ab5236",
})

sword_ascii = """
....................
.........##.........
........#Ws#........
.......#WsSD#.......
.......#WsSD#.......
.......#WsSD#.......
.......#WsSD#.......
.......#WsSD#.......
.......#WsSD#.......
.......#WsSD#.......
...#...#WsSD#...#...
..#GG###WsSD###GG#..
..#GGG##gRg##GGGG#..
...##GG#LlL#GG##....
......#LLLL#........
......#LllL#........
......#LLLL#........
.....#GGgGGG#.......
......#GGGG#........
.......####.........
"""

sword = Canvas.from_ascii(sword_ascii, palette)

print_ansi(sword, title="Legendary Broadsword (20x20)")
save_png(sword, "output/elemental_sword.png", scale=1, preview_scale=8)

rep = lint_sprite(sword)
print(rep.summary())
